### ISSUE TITLE
[Xbox Metadata] Connection closed

### ISSUE THREAD

**Issue by GiovanH** [Jeshibu/PlayniteExtensions#37]
All connections to the `https://marketplace.xbox.com/en-us/Search` are closed by the remote. The URLs generated still work in a browser. Connections likely need a user-agent set. 

```text
15-07 18:18:50.704|INFO |XboxMetadata#WebDownloader:Call to https://www.microsoft.com/msstoreapiprod/api/autosuggest?market=en-us&clientId=00000000-0000-0000-0000-000000000000&sources=Microsoft-Terms,Iris-Products,DCatAll-Products&filter=+ClientType:StoreWeb&counts=5,1,5&query=Halo%204 completed in 00:00:00.0231117
15-07 18:18:52.825|INFO |XboxMetadata#WebDownloader:Call to https://marketplace.xbox.com/en-us/Search?query=Halo%204&DownloadType=Game completed in 00:00:02.1431182
15-07 18:18:55.005|ERROR|XboxMetadata#XboxMetadata:Error fetching Xbox data
System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlayniteExtensions.Common.WebDownloader.<DownloadStringAsync>d__17.MoveNext() in D:\a\PlayniteExtensions\PlayniteExtensions\source\PlayniteExtensions.Common\WebDownloader.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlayniteExtensions.Common.WebDownloader.<DownloadStringAsync>d__16.MoveNext() in D:\a\PlayniteExtensions\PlayniteExtensions\source\PlayniteExtensions.Common\WebDownloader.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at XboxMetadata.Scrapers.XboxOneScraper.<GetDetailsAsync>d__7.MoveNext() in D:\a\PlayniteExtensions\PlayniteExtensions\source\XboxMetadata\Scrapers\XboxOneScraper.cs:line 25
```

**Comment by Jeshibu** [comment]
There always is a user agent set: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0` so that's not it. Does this still happen? Sometimes the website just has a fit.

**Comment by Jeshibu** [comment]
Assuming this is fixed now. If it isn't, feel free to reopen this issue or create another.
